### ISSUE TITLE
html escaping causing bad speech

### ISSUE THREAD

**Issue by arthurvaverko** [lib-x/edgetts#17]
take this for example 
"The villagers, inspired by the hunters' courage ..."

the single qout here gets translated to "#39"  and read like so as well

just remove thie https://github.com/lib-x/edgetts/blob/0506c06ffedbd2c7cffe67cb82362965a269519b/internal/communicate/communicate.go#L424C1-L425C1

**Comment by czyt** [comment]
fixed:thanks for your figure out
